# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/.devcontainer/Dockerfile'
        tags: |
          $(tag)
 
    - task: Docker@2
      displayName: Login to Azure registry
      inputs:
        containerRegistry: azurecr-oaf
        command: login

    - task: Docker@2
      displayName: push image to registry
      inputs:
        containerRegistry: azurecr-oaf
        repository: oneacrefund/rabbitmq-connector
        command: push
        tags: "$(tag)"

    - task: PublishBuildArtifacts@1
      displayName: Publish configuration package
      # Only publish main branch
      # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: rabbitmq
        publishLocation: Container