# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
       
    - script: |
        VERSION_TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo "1.0.4")
        echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
        echo "Tag: $VERSION_TAG"
      displayName: Get git tag


    - task: Docker@2
      displayName: Login to docker registry
      inputs:
        containerRegistry: 'azurecr-oaf'
        command: 'login'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: oaftech.azurecr.io/oneacrefund/rabbitmq-connector:$(VERSION_TAG)


    - script: docker images
      displayName: List all local images

    - script: echo $(VERSION_TAG)
      displayName: Echo Version Tag

    - script: |
        IMAGE_ID=$(docker images -q | head -n 1)
        docker tag $IMAGE_ID oaftech.azurecr.io/oneacrefund/rabbitmq-connector:$(VERSION_TAG)
      displayName: Tag latest image

      
    - script: |
        docker images
        docker push oaftech.azurecr.io/oneacrefund/rabbitmq-connector:1.0.9
      displayName: manual push to acr

    - task: Docker@2
      displayName: push image to registry
      inputs:
        containerRegistry: azurecr-oaf
        repository: oaftech.azurecr.io/oneacrefund/rabbitmq-connector
        command: push
        tags: $(VERSION_TAG)

    - script: |
        docker images
        docker push oaftech.azurecr.io/oneacrefund/rabbitmq-connector:1.0.9
      displayName: manual push to acr

    - task: PublishBuildArtifacts@1
      displayName: Publish configuration package
      # Only publish main branch
      # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: rabbitmq
        publishLocation: Container
